language: node_js
node_js: "4.2"
script:
- node .
before_install:
#- openssl aes-256-cbc -K $encrypted_f35a97c68e01_key -iv $encrypted_f35a97c68e01_iv
#  -in datasources.json.enc -out server\\datasources.json -d
install:
- "npm install"