language: node_js
node_js: "4.2"
before_script:
- echo $DSKEY | gpg --pass-phrase-fd 0 server/datasources.json.gpg
- "ls -l ./server"
- "ls -l ./"
- "cat ./server/datasources.json"
- "cat ./datasources.json"
env:
    global:
        secure: oxKDGiWRvaOLQyvd4iFRPgXqN0MXot7kYPlA86MPgaCLU/YbJ2U/4APLVCXg9sY8yPgV6GI+AhOvuOTDspS9QdiKUzjsJJQ+gsx3VeAZzPFRQ6sVyLixuqCbJZYLyp9JPEXi+ALHNe6CUYkQVKdALxRPGEfZ/5SW8uZ8EJ0aUVUZCFEtDN4GjTIs3NcgIK4JEDrOxV1mSeS7XvcfP5cV0cbmM04I/q0HnT09TU7VM5FbnRj1c2OWd+Fa/x0k7avpMelfiSK+M37CVIEwpyD1zRcsjwZk1TpiZRsOmkJCgJe0apZsmpyWw2kegfzZe5zG3RWHzHWD2Eh+9+ul7tZJfaxMimZ2o9DC9KqLUInKntXeRoPgyBODrwJHiEC5oNlVglqxQtOd+cgv+JdA5kfxNUsHhXkpGXV+sX5Q4fssgVBpgEPMpihnww5g0oPE3K5rWZ9WK6St9yhJs2VrRBu7KocSoCIOSRHOpVWuYQ8Lpviy9MQABW1GeqixrWTxpIDMxFyNCpnitYQzCF2Y1tC3jANAAQMHg1ZOK9IXz/RbKcwXFKWIiLDhATQWdMGmAPdYfGHoqGRDbjN6wrj+oOkjeoNy2fvKY2sG1t+gmnVVoo5LGOpzEJUetM+Y7Dgp3p3iyLj03IABgIRzOq5yifmXsUB/eCQPvNKkaeLJftXnhew=
