language: node_js
node_js: '4.2'
before_script:
- echo $DSKEY | gpg --passphrase-fd 0 server/datasources.json.asc
- echo $DSKEY | gpg --passphrase-fd 0 server/datasources.production.json.asc
env:
  global:
    secure: oxKDGiWRvaOLQyvd4iFRPgXqN0MXot7kYPlA86MPgaCLU/YbJ2U/4APLVCXg9sY8yPgV6GI+AhOvuOTDspS9QdiKUzjsJJQ+gsx3VeAZzPFRQ6sVyLixuqCbJZYLyp9JPEXi+ALHNe6CUYkQVKdALxRPGEfZ/5SW8uZ8EJ0aUVUZCFEtDN4GjTIs3NcgIK4JEDrOxV1mSeS7XvcfP5cV0cbmM04I/q0HnT09TU7VM5FbnRj1c2OWd+Fa/x0k7avpMelfiSK+M37CVIEwpyD1zRcsjwZk1TpiZRsOmkJCgJe0apZsmpyWw2kegfzZe5zG3RWHzHWD2Eh+9+ul7tZJfaxMimZ2o9DC9KqLUInKntXeRoPgyBODrwJHiEC5oNlVglqxQtOd+cgv+JdA5kfxNUsHhXkpGXV+sX5Q4fssgVBpgEPMpihnww5g0oPE3K5rWZ9WK6St9yhJs2VrRBu7KocSoCIOSRHOpVWuYQ8Lpviy9MQABW1GeqixrWTxpIDMxFyNCpnitYQzCF2Y1tC3jANAAQMHg1ZOK9IXz/RbKcwXFKWIiLDhATQWdMGmAPdYfGHoqGRDbjN6wrj+oOkjeoNy2fvKY2sG1t+gmnVVoo5LGOpzEJUetM+Y7Dgp3p3iyLj03IABgIRzOq5yifmXsUB/eCQPvNKkaeLJftXnhew=
deploy:
  provider: codedeploy
  access_key_id: AKIAJB3FLE62BOSU3CPQ
  secret_access_key:
    secure: AffilpBi4xdSTQKEq4wvG8G+JmC871h5FC6/XWyNEIH5t959/8Ox+2lAUF/6JMljDDcTLR5E8XM8UF13H1UMninvg6jCvz1Fwksbyq8ASrXJRQUSreKopn8eVp4mOENqzd94nu3jZ6PyzJ/8uoa0yXgtlHLhd4Xt89SAoDWIJ9RCHiuYFxcvb+H8l0hmPBwWiihab5KZ4/VTdEsahuGxcnKtkSBddUtEzu5dSjKhUn4T5Y9sk4D9tK4EFmufSEpCiH3JssmCCKCMLwVLh1M6AVugFk/1KaZWeuiCAQGN+nY4R1pdh28SHrd/O/+9HzmTLS81mV8AzBGbJi1m4coLEn1xFm42TrgQktoxDZf9XqvSB7k6MzIb1MaNvko7opt+Jni+65CDLq6n26lm9ZIFCHwxFIsie6MQz7nYKEOfjq3uyOcIWmLzvd0iL96XKvaJCuTr9cBS2H/ye4eQr5PwMP3hpvOHm90M7Ww8Pl2m+/nFPyg204Fa7abG6hj7F6JYWs5p9HsGLjseQ5069oEBygfs7Kth6Wj5lX7WeI0nOFjGFRsnq8DhJ4ipsChzqGMSjJNYmLEcmjm18jkqWZIZNFF8CT0oE3P9bFSPa88fJW89mtv3FMTkCyw/ThfQiaWeL2Cowgr5y2u+YCL6ntm11vjT+2psd9xn5hIficRWT/A=
  skip_cleanup: true
  application: kcoffey-blog-app
  deployment_group: kcoffey-blog-app-deploy-role
  on:
    tags: true
    repo: kevdougful/mysite
